name: 'Telegram Message'
description: 'Send Message to Kode CI/CD Telegram Group'

inputs:
  message:
    description: 'Message to send'
    required: false
    default: 'Hello world from ${{ github.repository }}'

  notification:
    description: 'Push Notification'
    required: false
    default: false

  token:
    description: 'Telegram Token'
    required: true

  to:
    description: 'Telegram Token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: appleboy/telegram-action@master
      with:
        message: "${{ inputs.message }}"
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        disable_notification: ${{ inputs.notification }}
